ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION}

USER root

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/usr/local/bin:${PATH}"

### update apt repo
RUN apt-get update && apt-get install -y \
    software-properties-common && \
    add-apt-repository universe && \
    add-apt-repository multiverse

### install utils
RUN apt-get update && apt-get install -y \
        git vim sudo \
        libva-dev \
        pciutils \
        kmod

# X11 forwarding and xcb
RUN apt-get install -y x11-apps libx11-6 xauth libxext6 libxrender1 libxtst6 libxi6 libxcb-xinerama0

# python 3
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get install -y python3 python3-dev python3-venv

# Set up Virtual Environment
RUN set -x && \
    python3 -m venv /venv-dxnn-hw-acc --system-site-packages

# DX-RT, DX-APP
RUN apt-get update && \
    apt-get install -y \
    sudo \
    build-essential \
    make \
    cmake \
    ninja-build \
    git \
    curl \
    wget \
    vim \
    nano \
    unzip \
    tar \
    zip \
    openssh-client \
    libcurl4-openssl-dev \
    zlib1g-dev \
    libopencv-dev \
    python3-dev \
    python3-setuptools \
    python3-pip \
    python3-tk \
    python3-lxml \
    python3-six \
    python3-venv \
    libjpeg-dev \
    libtiff5-dev \
    libpng-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libxvidcore-dev \
    libx264-dev \
    libxine2-dev \
    libv4l-dev \
    v4l-utils \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgtk2.0-dev \
    libfreetype* && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt

# git clone
RUN git clone --depth 1 -b intel-gmmlib-22.6.0 https://github.com/intel/gmmlib.git && \
    git clone --depth 1 -b 2.22.0 https://github.com/intel/libva.git && \
    git clone --depth 1 -b 2.22.0 https://github.com/intel/libva-utils.git && \
    git clone --depth 1 -b intel-media-24.3.4 https://github.com/intel/media-driver.git

# install gcc-9, g++-9
ENV GCC_VERSION=9
RUN apt update && apt-get install -y gcc-${GCC_VERSION} g++-${GCC_VERSION} lsb-release

# install cmake and meson and dependencies package for libva, libva-utils, media-driver
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Install build dependencies..." && \
    UBUNTU_VERSION=$(lsb_release -rs) && \
    if [ "$UBUNTU_VERSION" = "24.04" ]; then \
      echo "Ubuntu 24.04" && \
      pip3 install meson==1.3 --break-system-packages && \
      pip3 install cmake==3.17 --break-system-packages && \
      apt-get install -y \
              libxfixes-dev autoconf libtool libdrm-dev \
              xorg xorg-dev openbox libx11-dev \
              libgl1-mesa-dev libxcb-dri3-0 libxcb-dri3-dev; \
    elif [ "$UBUNTU_VERSION" = "22.04" ]; then \
      echo "Installing development tools" && \
      pip3 install meson==1.3 && \
      pip3 install cmake==3.17 && \
      apt-get install -y \
              libxfixes-dev autoconf libtool \
              libx11-dev \
              libgl1-mesa-dev libxcb-dri3-0 libxcb-dri3-dev; \
    elif [ "$UBUNTU_VERSION" = "20.04" ]; then \
      echo "Installing development tools" && \
      pip3 install meson==1.3 && \
      pip3 install cmake==3.17 && \
      apt-get install -y \
              libxfixes-dev autoconf libtool libdrm-dev \
              xorg xorg-dev openbox libx11-dev \
              libgl1-mesa-dev libgl1-mesa-glx libxcb-dri3-0 libxcb-dri3-dev; \      
    else \
      echo "Unspported Ubuntu version: $UBUNTU_VERSION" && exit 1; \
    fi

RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Building gmmlib..." && \
    cd gmmlib && \
    mkdir -p build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=/usr/bin/gcc-${GCC_VERSION} \
          -DCMAKE_CXX_COMPILER=/usr/bin/g++-${GCC_VERSION} ../ && \
    cmake --build . --config Release -j $num_cores_to_use && \
    sudo cmake --install . && \
    cd ../../

# build libva
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Building libva..." && \
    cd libva && \
    meson libva_build --buildtype release -Dwith_x11=yes && \
    ninja -C libva_build && \
    sudo env "PATH=$PATH" ninja -C libva_build install && \
    cd ..  


# build libva-utils
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Building libva-utils..." && \
    cd libva-utils && \
    meson libva_build --buildtype release && \
    ninja -C libva_build && \
    sudo env "PATH=$PATH" ninja -C libva_build install && \
    cd ..
    
# build media-driver
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Building media-driver..." && \
    cd media-driver && \
    mkdir -p build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release CMAKE_C_COMPILER=/usr/bin/gcc-${GCC_VERSION} -DCMAKE_CXX_COMPILER=/usr/bin/g++-${GCC_VERSION} ../ && \
    make -j $(($(nproc) / 2)) && \
    sudo make install && \
    cd ../../

# build gstreamer
# python 3.11
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get install -y python3.11 python3.11-dev python3.11-venv

# Set up Virtual Environment
RUN python3.11 -m venv /venv-gst --system-site-packages

RUN set -x && \
    . /venv-gst/bin/activate && \
    echo "Upgrade pip wheel setuptools..." && \
    UBUNTU_VERSION=$(lsb_release -rs) && \
    if [ "$UBUNTU_VERSION" = "24.04" ]; then \
      pip install --upgrade "setuptools<65"; \
    elif [ "$UBUNTU_VERSION" = "22.04" ]; then \
      pip install --upgrade "pip wheel setuptools<65"; \
    elif [ "$UBUNTU_VERSION" = "20.04" ]; then \
      pip install --upgrade "pip wheel setuptools<65"; \
    else \
      echo "Unspported Ubuntu version: $UBUNTU_VERSION" && exit 1; \
    fi

RUN set -x && \
    echo "clone gstreamer..." && \
    git clone --depth 1 -b 1.24.11 https://gitlab.freedesktop.org/gstreamer/gstreamer.git && \
    echo "Install build dependencies..." && \
    sudo apt install -y flex bison libunwind-dev nasm && \
    . /venv-gst/bin/activate && \
    UBUNTU_VERSION=$(lsb_release -rs) && \
    if [ "$UBUNTU_VERSION" = "24.04" ]; then \
        pip3 install meson==1.3 --break-system-packages; \
    else \
        pip3 install meson==1.3; \
    fi

# temporary solution for access denied sourceforge URL on internal-network
ADD deps/fdk-acc-2.0.2.tar.gz /opt/gstreamer/subprojects/.
ADD deps/lame-3.100.tar.gz /opt/gstreamer/subprojects/.

RUN set -x && \
    . /venv-gst/bin/activate && \
    echo "Building gstreamer..." && \
    cd gstreamer && \
    meson setup builddir \
    -Dbase=enabled \
    -Dgood=enabled \
    -Dgst-plugins-good:qt5=enabled \
    -Dgst-plugins-good:qt6=enabled \
    -Dbad=enabled \
    -Dugly=enabled \
    -Dvaapi=enabled && \
    meson compile -C builddir && \
    meson install -C builddir
    
ENV LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/
ENV LIBVA_DRIVER_NAME=iHD
ENV GST_VAAPI_ALL_DRIVERS=1
ENV GST_PLUGIN_PATH=/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0

RUN set -x && \
    echo "check gst-plugin-vaapi..." && \
    gst-inspect-1.0 --version && \
    gst-inspect-1.0 vaapi
    
    
# build QT5
# enable source package apt repository
RUN echo "deb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs) main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs)-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb-src http://archive.ubuntu.com/ubuntu $(lsb_release -cs)-security main restricted universe multiverse" >> /etc/apt/sources.list

# update pakcage list
RUN apt-get update && \
    apt-get build-dep -y qtbase5-dev && \
# for build essential
    apt-get install -y \
    build-essential perl python3 git && \
# for libxcb
    apt-get install -y \
    '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev && \
# for QT Multimedia
    apt-get install -y libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y \
    build-essential perl python3 git libgl1-mesa-dev libx11-dev mesa-utils libopengl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://download.qt.io/official_releases/qt/5.15/5.15.16/single/qt-everywhere-opensource-src-5.15.16.tar.xz && \
# RUN wget https://download.qt.io/official_releases/qt/5.15/5.15.11/single/qt-everywhere-opensource-src-5.15.11.tar.xz && \
    tar xf qt-everywhere-opensource-src-5.15.16.tar.xz

# hijack code for build error of '-std=c++1z' with gcc-13
RUN cd qt-everywhere-src-5.15.16 && \
    sed -i '6i #include <cstdint>' qtlocation/src/3rdparty/mapbox-gl-native/include/mbgl/util/geometry.hpp && \
    sed -i '7i #include <cstdint>' qtlocation/src/3rdparty/mapbox-gl-native/include/mbgl/util/string.hpp && \
    sed -i '4i #include <cstdint>' qtlocation/src/3rdparty/mapbox-gl-native/src/mbgl/gl/stencil_mode.hpp

# Build QT5
RUN set -x && \
    # . /venv-dxnn-hw-acc/bin/activate && \
    cd qt-everywhere-src-5.15.16 && \
    ./configure -prefix /usr/local/qt5 \
            -opensource \
            -confirm-license \
            -opengl es2 \
            -skip webengine \
            -nomake examples \
            -nomake tests && \
    gmake -j $(($(nproc) / 2)) && \
    gmake install && \
    /usr/local/qt5/bin/qmake -v
    
    
# build OpenCV
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Install build dependencies..." && \
    python -m pip install numpy --upgrade && \
    UBUNTU_VERSION=$(lsb_release -rs) && \
    if [ "$UBUNTU_VERSION" = "24.04" ]; then \
        apt-get update && \
        apt-get install -y \
        build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
        python3-dev libtbb-dev libjpeg-dev libpng-dev libtiff-dev \
        libopenjp2-7-dev liblapack-dev libblas-dev libvtk9-dev default-jdk ffmpeg && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*; \
    else \
        apt-get update && \
        apt-get install -y \
        build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
        python3-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev \
        libopenjp2-7-dev liblapack-dev libblas-dev libvtk7-dev default-jdk ffmpeg && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*; \
    fi

RUN set -x && \
    echo "Clone opencv source..." && \
    mkdir -p /opt/util && cd /opt/util && \
    wget -O opencv.4.10.0.zip https://github.com/opencv/opencv/archive/4.10.0.zip && \
    wget -O opencv_contrib.4.10.0.zip https://github.com/opencv/opencv_contrib/archive/4.10.0.zip && \
    rm -rf /opt/util/opencv-4.10.0 && \
    rm -rf /opt/util/opencv_contrib-4.10.0 && \
    unzip opencv.4.10.0.zip && \
    unzip opencv_contrib.4.10.0.zip

RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Build opencv..." && \
    cd /opt/util/opencv-4.10.0 && \
    mkdir builddir && \
    cd builddir && \
    cmake \
            -D CMAKE_INSTALL_PREFIX=/usr/local \
            -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.10.0/modules \
            -D CMAKE_BUILD_TYPE=RELEASE \
            -D WITH_TBB=ON -D WITH_IPP=OFF -D WITH_1394=OFF \
            -D BUILD_WITH_DEBUG_INFO=OFF -D BUILD_DOCS=OFF \
            -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON \
            -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF \
            -D WITH_QT=ON -D WITH_GTK=ON -D WITH_OPENGL=ON -D WITH_PNG=ON\
            -D WITH_V4L=ON -D WITH_FFMPEG=OFF -D WITH_XINE=ON -D BUILD_NEW_PYTHON_SUPPORT=ON \
            -D OPENCV_GENERATE_PKGCONFIG=ON -D WITH_CUDA=OFF -D WITH_FREETYPE=ON \
            -D PYTHON3_EXECUTABLE=$(which python3) \
            -D PYTHON3_INCLUDE_DIR=$(python3 -c "from sysconfig import get_paths as gp; print(gp()['include'])") \
            -D PYTHON3_PACKAGES_PATH=$(python3 -c "from sysconfig import get_paths as gp; print(gp()['purelib'])") \
            -D PYTHON3_LIBRARY=$(python3 -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))") \
            -D PYTHON3_NUMPY_INCLUDE_DIRS=$(python3 -c "import numpy; print(numpy.get_include())") \
            -D BUILD_opencv_python3=ON -D HIGHGUI_ENABLE_PLUGINS=ON \
            -D HIGHGUI_PLUGIN_LIST="all" \
            -D CMAKE_POLICY_DEFAULT_CMP0072=NEW \
            -D WITH_VTK=OFF \
            ../

RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    cd /opt/util/opencv-4.10.0/builddir && \
    make -j $(($(nproc) / 2))
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    cd /opt/util/opencv-4.10.0/builddir && \
    sudo make install && ldconfig

# set ENV for QT
ENV LD_LIBRARY_PATH=/usr/local/qt5/lib:${LD_LIBRARY_PATH}
ENV QT_PLUGIN_PATH=/usr/local/qt5/plugins
ENV QML2_IMPORT_PATH=/usr/local/qt5/qml
ENV QT_QPA_PLATFORM=xcb

WORKDIR /deepx/dx_rt
ADD archives/dx_rt.tar.gz /deepx/dx_rt/
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Build dx_rt..." && \
    ./install.sh --dep && \
    ./build.sh --install

WORKDIR /deepx/dx_app
ARG FILE_DXAPP=archives/dx_app.tar.gz
ARG FILE_DXAPP_ASSETS=res/dx_app_assets.tar.gz
ADD ${FILE_DXAPP} /deepx/dx_app/
ADD ${FILE_DXAPP_ASSETS} /deepx/dx_app/
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "Build dx_app..." && \
    ./install.sh --all
# The application must be built at container runtime for GPU acceleration to be applied.
# RUN set -x && \
#     . /venv-dxnn-hw-acc/bin/activate && \
#     ./build.sh
    
WORKDIR /deepx/dx_stream
ARG FILE_DXSTREAM=archives/dx_stream.tar.gz
ARG FILE_DXSTREAM_ASSETS=res/dx_stream_samples.tar.gz
ADD ${FILE_DXSTREAM} /deepx/dx_stream/
ADD ${FILE_DXSTREAM_ASSETS} /deepx/dx_stream/dx_stream/
RUN set -x && \
    . /venv-dxnn-hw-acc/bin/activate && \
    echo "install dependancies for dx_stream..." && \
    sudo ./install.sh && \

    echo "Build dx_stream..." && \
    sudo ./build.sh --install

RUN ln -s /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstdxstream.so /usr/local/lib/x86_64-linux-gnu/gstreamer-1.0/libgstdxstream.so

# copy DX-CLIP-DEMO
WORKDIR /deepx/dx-clip-demo
ARG FILE_DXCLIPDEMO=archives/dx_clip_demo.tar.gz
ARG FILE_DXCLIPDEMO_ASSETS=res/clip_assets.tar.gz
ARG AARC_PATH=amd64
ADD ${FILE_DXCLIPDEMO} /deepx/dx-clip-demo/.
ADD ${FILE_DXCLIPDEMO_ASSETS} /deepx/dx-clip-demo/.
RUN ./scripts/${AARC_PATH}/setup_clip_demo_app_opencv.sh --dxrt_src_path=/deepx/dx_rt/
RUN ./scripts/${AARC_PATH}/setup_clip_demo_app_pyqt.sh --dxrt_src_path=/deepx/dx_rt/

WORKDIR /deepx

RUN apt-get update && \
    apt-get install -y \
    vim fim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["bash", "-c", ". /venv-dxnn-hw-acc/bin/activate && pushd /deepx/dx_app && ./build.sh && popd && /usr/local/bin/dxrtd"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]

