#!/bin/bash
# One-command launcher for the yolo26n-pose Stretch Coach mini-game.
# Generated by DX Agent-Driven Dev
#
# Default: run on the bundled demo video and SAVE an annotated output video.
# Live camera:   bash run.sh --camera 0
# Other video:   bash run.sh --video /path/to/clip.mp4
# Custom model:  bash run.sh --model /path/to/yolo26n-pose.dxnn

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Auto-detect suite root (for cross-project references) ---
SUITE_ROOT="$SCRIPT_DIR"
while [ "$SUITE_ROOT" != "/" ]; do
    if [ -d "$SUITE_ROOT/dx-runtime" ] && [ -d "$SUITE_ROOT/dx-compiler" ]; then
        break
    fi
    SUITE_ROOT="$(dirname "$SUITE_ROOT")"
done
[ "$SUITE_ROOT" = "/" ] && echo "[WARN] Cannot find dx-all-suite root (dx-runtime/ + dx-compiler/ siblings)"
RUNTIME_DIR="$SUITE_ROOT/dx-runtime"

# --- Activate venv (relocatable; do NOT re-run setup.sh) ---
if [ -d "$SCRIPT_DIR/venv" ]; then
    source "$SCRIPT_DIR/venv/bin/activate"
elif [ -d "$SCRIPT_DIR/.venv" ]; then
    source "$SCRIPT_DIR/.venv/bin/activate"
elif [ -x "$RUNTIME_DIR/venv-dx-runtime/bin/python" ]; then
    source "$RUNTIME_DIR/venv-dx-runtime/bin/activate"
else
    echo "[WARN] no venv found — run 'bash setup.sh' first if imports fail"
fi

# --- Resolve model (precompiled .dxnn) ---
DEFAULT_MODEL="$RUNTIME_DIR/dx_app/assets/models/yolo26n-pose.dxnn"
MODEL="$DEFAULT_MODEL"

# --- Default input: bundled demo video (self-contained) ---
if [ -f "$SCRIPT_DIR/sample/stretching_demo.mp4" ]; then
    DEFAULT_VIDEO="$SCRIPT_DIR/sample/stretching_demo.mp4"
else
    DEFAULT_VIDEO="$RUNTIME_DIR/dx_app/sample/videos/stretching_demo.mp4"
fi

# --- Parse a few convenience flags; pass everything else through ---
EXTRA_ARGS=()
INPUT_SET=0
while [ "$#" -gt 0 ]; do
    case "$1" in
        --model) MODEL="$2"; shift 2 ;;
        --video|--camera|--rtsp|--image) INPUT_SET=1; EXTRA_ARGS+=("$1" "$2"); shift 2 ;;
        *) EXTRA_ARGS+=("$1"); shift ;;
    esac
done

if [ ! -f "$MODEL" ]; then
    echo "[ERROR] Model not found: $MODEL"
    echo "Usage: bash run.sh [--model <path>] [--video <file> | --camera <id>] [--display]"
    echo "  Precompiled model expected at: $DEFAULT_MODEL"
    echo "  Download:  cd $RUNTIME_DIR/dx_app && ./setup.sh --models yolo26n-pose"
    exit 1
fi
echo "[INFO] Model: $MODEL"

# --- Belt-and-suspenders PYTHONPATH for standalone runs (walker is primary) ---
_v3_search="$SCRIPT_DIR"
while [ "$_v3_search" != "/" ]; do
    if [ -d "$_v3_search/src/python_example/common" ]; then
        export PYTHONPATH="$_v3_search/src/python_example${PYTHONPATH:+:$PYTHONPATH}"
        break
    fi
    _v3_search="$(dirname "$_v3_search")"
done

if [ "$INPUT_SET" -eq 1 ]; then
    # User chose the input (e.g. --camera 0). Default to on-screen display.
    echo "[INFO] Input: user-specified"
    exec python "$SCRIPT_DIR/yolo26n_pose_stretch_sync.py" --model "$MODEL" "${EXTRA_ARGS[@]}"
else
    # Default demo: run on the bundled video and SAVE an annotated output video.
    echo "[INFO] Input: $DEFAULT_VIDEO (saving annotated output to ./output)"
    exec python "$SCRIPT_DIR/yolo26n_pose_stretch_sync.py" --model "$MODEL" \
        --video "$DEFAULT_VIDEO" --save --save-dir "$SCRIPT_DIR/output" --no-display "${EXTRA_ARGS[@]}"
fi
