#!/bin/bash
# Environment setup for yolo26n-pose Stretch Coach mini-game
# Generated by DX Agent-Driven Dev

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- 1. Virtual environment detection & activation ---
# Search upward for the dx-runtime shared venv (preferred — has dx_engine)
RUNTIME_VENV=""
_search="$SCRIPT_DIR"
for _i in 1 2 3 4 5; do
    _search="$(dirname "$_search")"
    if [ -d "$_search/venv-dx-runtime" ]; then
        RUNTIME_VENV="$_search/venv-dx-runtime"
        break
    fi
done

LOCAL_VENV="$SCRIPT_DIR/.venv"

if [ -n "$RUNTIME_VENV" ] && [ -d "$RUNTIME_VENV" ]; then
    echo "[INFO] Activating dx-runtime venv: $RUNTIME_VENV"
    source "$RUNTIME_VENV/bin/activate"
elif [ -d "$LOCAL_VENV" ]; then
    echo "[INFO] Activating local venv: $LOCAL_VENV"
    source "$LOCAL_VENV/bin/activate"
else
    echo "[INFO] Creating local venv at $LOCAL_VENV ..."
    python3 -m venv "$LOCAL_VENV"
    source "$LOCAL_VENV/bin/activate"
    pip install --upgrade pip
fi

# --- 2. Install dependencies ---
# OpenCV policy (HARD GATE): GUI-enabled opencv-python so --display / --camera work.
pip uninstall -y opencv-python-headless >/dev/null 2>&1 || true
pip install opencv-python numpy >/dev/null 2>&1 || pip install opencv-python numpy

# --- 2b. Vendor the shared framework so the app is PORTABLE (HARD GATE) ---
if [ ! -d "$SCRIPT_DIR/common" ]; then
    _vsrc=""; _vd="$SCRIPT_DIR"
    while [ "$_vd" != / ]; do
        if [ -d "$_vd/src/python_example/common" ]; then _vsrc="$_vd/src/python_example/common"; break; fi
        if [ -d "$_vd/dx-runtime/dx_app/src/python_example/common" ]; then _vsrc="$_vd/dx-runtime/dx_app/src/python_example/common"; break; fi
        _vd="$(dirname "$_vd")"
    done
    if [ -n "$_vsrc" ]; then
        echo "[setup] vendoring framework: $_vsrc -> ./common"
        cp -r "$_vsrc" "$SCRIPT_DIR/common"
        find "$SCRIPT_DIR/common" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true
    else
        echo "[setup] WARN: ./common absent and dx_app framework not found — 'common' imports may fail."
    fi
fi

# --- 3. Verify dx_engine ---
if ! python -c "import dx_engine" 2>/dev/null; then
    echo "[FATAL] dx_engine not available in the active venv."
    echo "  Fix: cd $(cd "$SCRIPT_DIR/../.." && pwd) && ./install.sh && ./build.sh"
    echo "  Then re-run: bash setup.sh"
    exit 1
fi
echo "[OK] dx_engine available"

echo "[INFO] Setup complete. Run: bash run.sh"
