# dx-all-suite/.github/workflows/gh-cloud-update-submodule.yml
name: Update Submodule

on:
  repository_dispatch:
    types:
      - update-submodule # dx-runtime staging push로부터의 원래 트리거
      - update-submodule-from-child # dx-runtime/compiler/modelzoo main branch 업데이트로부터의 새로운 트리거

permissions: write-all

jobs:
  update-submodule:
    runs-on:
      - self-hosted
      - sdk
    timeout-minutes: 5
    steps:
      - name: Clean Workspace
        run: |
          sudo rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # 'update-submodule-from-child'에 의해 트리거된 경우, ref는 parent_ref (main)여야 합니다.
          # 'update-submodule' (dx-runtime의 staging push)에 의해 트리거된 경우, ref는 staging입니다.
          ref: ${{ github.event.client_payload.parent_ref || github.event.client_payload.ref }}
          submodules: recursive
          fetch-tags: true
          fetch-depth: 0
          token: ${{ secrets.GC_DCI_TOKEN }}

      - name: Update Submodule
        run: |
          SUBMODULE_NAME="${{ github.event.client_payload.submodule_name || github.event.client_payload.name }}"
          SUBMODULE_SHA="${{ github.event.client_payload.submodule_sha || github.event.client_payload.sha }}"
          TARGET_BRANCH="${{ github.event.client_payload.parent_ref || github.event.client_payload.ref }}"

          echo "Updating submodule $SUBMODULE_NAME to $SUBMODULE_SHA on $TARGET_BRANCH branch."

          # Fetch latest changes and reset to remote branch to avoid divergence
          git fetch origin
          git checkout $TARGET_BRANCH
          git reset --hard origin/$TARGET_BRANCH

          git submodule update --init --recursive $SUBMODULE_NAME

          cd $SUBMODULE_NAME
          git fetch origin
          git checkout $SUBMODULE_SHA
          cd ..

      - name: Generate DATE ENV
        run: |
          echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Commit Submodule Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.client_payload.parent_ref || github.event.client_payload.ref }}
          commit_message: "ci(${{env.DATE}}): Update ${{ github.event.client_payload.submodule_name || github.event.client_payload.name }}"
          commit_options: "--no-verify --allow-empty"
